### ISSUE TITLE
Provide a concrete release for metabot

### ISSUE THREAD

**Issue by RaphaelVogel** [packethost/metabot#2]
Images with a concrete version are preferred by Gardener for compliance reasons.
(https://github.com/gardener/gardener-extensions/blob/master/controllers/provider-packet/charts/images.yaml#L55  refers to latest)

**Comment by deitch** [comment]
Done. Release is out. See https://hub.docker.com/layers/packethost/metabot/v1.0.0/images/sha256-197b25b1a210cc69737c3c4453bce77ef9641d3692413a95ecffeff40d0e84a3

**Comment by deitch** [comment]
Done. Release is out. See https://hub.docker.com/layers/packethost/metabot/v1.0.0/images/sha256-197b25b1a210cc69737c3c4453bce77ef9641d3692413a95ecffeff40d0e84a3
